-- MySQL Script generated by MySQL Workbench
-- Fri May 29 11:37:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vsarena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vsarena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vsarena` DEFAULT CHARACTER SET utf8 ;
USE `vsarena` ;

-- -----------------------------------------------------
-- Table `vsarena`.`Cupones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Cupones` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Cupones` (
  `idCupon` INT NOT NULL AUTO_INCREMENT,
  `nombreCupon` VARCHAR(255) NULL,
  `porcentajeDescuento` DECIMAL NULL,
  `estadoCupon` VARCHAR(255) NULL,
  `inicioCupon` DATETIME NULL,
  `finCupon` DATETIME NULL,
  PRIMARY KEY (`idCupon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsarena`.`Equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Equipos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Equipos` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `equipo` VARCHAR(255) NULL,
  `avatarEquipo` VARCHAR(255) NULL,
  `lider_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEquipo`, `lider_idUsuario`),
  CONSTRAINT `fk_Equipos_Usuarios1`
    FOREIGN KEY (`lider_idUsuario`)
    REFERENCES `vsarena`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipos_Usuarios1_idx` ON `vsarena`.`Equipos` (`lider_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NULL,
  `emaiUsuario` VARCHAR(255) NULL,
  `passUsuario` VARCHAR(255) NULL,
  `avatarUsuario` VARCHAR(255) NULL,
  `saldoEfectivo` FLOAT NULL,
  `saldoMonVir` FLOAT NULL,
  `isAdmin` BOOLEAN NULL,
  `Cupones_idCupon` INT NULL,
  `Equipos_idEquipo` INT NULL,
  PRIMARY KEY (`idUsuario`, `Cupones_idCupon`, `Equipos_idEquipo`),
  CONSTRAINT `fk_Usuarios_Cupones1`
    FOREIGN KEY (`Cupones_idCupon`)
    REFERENCES `vsarena`.`Cupones` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `vsarena`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuarios_Cupones1_idx` ON `vsarena`.`Usuarios` (`Cupones_idCupon` ASC);

CREATE INDEX `fk_Usuarios_Equipos1_idx` ON `vsarena`.`Usuarios` (`Equipos_idEquipo` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Juegos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Juegos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Juegos` (
  `idJuego` INT NOT NULL AUTO_INCREMENT,
  `juego` VARCHAR(255) NULL,
  `descripcionJuego` VARCHAR(255) NULL,
  `imgJuego` VARCHAR(255) NULL,
  `plataforma` VARCHAR(255) NULL,
  PRIMARY KEY (`idJuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsarena`.`Torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Torneos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Torneos` (
  `idTorneo` INT NOT NULL AUTO_INCREMENT,
  `torneo` VARCHAR(255) NULL,
  `cantMaxEquipos` INT NULL,
  `modalidad` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `fechaInicio` DATETIME NULL,
  `fechaFin` DATETIME NULL,
  `fasesDeGrupo` TINYINT NULL,
  `Juegos_idJuegos` INT NOT NULL,
  PRIMARY KEY (`idTorneo`, `Juegos_idJuegos`),
  CONSTRAINT `fk_Torneos_Juegos1`
    FOREIGN KEY (`Juegos_idJuegos`)
    REFERENCES `vsarena`.`Juegos` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Torneos_Juegos1_idx` ON `vsarena`.`Torneos` (`Juegos_idJuegos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Rondas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Rondas` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Rondas` (
  `idRonda` INT NOT NULL,
  `NombreRonda` VARCHAR(255) NULL,
  `Torneos_idTorneos` INT NOT NULL,
  PRIMARY KEY (`idRonda`, `Torneos_idTorneos`),
  CONSTRAINT `fk_Rondas_Torneos1`
    FOREIGN KEY (`Torneos_idTorneos`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Rondas_Torneos1_idx` ON `vsarena`.`Rondas` (`Torneos_idTorneos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Grupos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Grupos` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `NombreGrupo` VARCHAR(255) NULL,
  `Torneos_idTorneos` INT NOT NULL,
  PRIMARY KEY (`idGrupo`, `Torneos_idTorneos`),
  CONSTRAINT `fk_Grupos_Torneos1`
    FOREIGN KEY (`Torneos_idTorneos`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Grupos_Torneos1_idx` ON `vsarena`.`Grupos` (`Torneos_idTorneos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Enfrentamientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Enfrentamientos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Enfrentamientos` (
  `idEnfrentamiento` INT NOT NULL,
  `NombreEnfrentamiento` VARCHAR(255) NULL,
  `Ganador` VARCHAR(255) NULL,
  `Rondas_idRondas` INT NULL,
  `Grupos_idGrupos` INT NULL,
  `FechaEnfrentamiento` DATETIME NULL,
  PRIMARY KEY (`idEnfrentamiento`, `Rondas_idRondas`, `Grupos_idGrupos`),
  CONSTRAINT `fk_Enfrentamientos_Rondas1`
    FOREIGN KEY (`Rondas_idRondas`)
    REFERENCES `vsarena`.`Rondas` (`idRonda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfrentamientos_Grupos1`
    FOREIGN KEY (`Grupos_idGrupos`)
    REFERENCES `vsarena`.`Grupos` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Enfrentamientos_Rondas1_idx` ON `vsarena`.`Enfrentamientos` (`Rondas_idRondas` ASC);

CREATE INDEX `fk_Enfrentamientos_Grupos1_idx` ON `vsarena`.`Enfrentamientos` (`Grupos_idGrupos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Ventas` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `cantidadProductos` INT NULL,
  `totalVenta` DECIMAL NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `Usuarios_idUsuario`),
  CONSTRAINT `fk_Ventas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `vsarena`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ventas_Usuarios1_idx` ON `vsarena`.`Ventas` (`Usuarios_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Productos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(255) NULL,
  `precioEfectivo` FLOAT NULL,
  `precioMonVirtual` FLOAT NULL,
  `stock` INT NULL,
  `descripcion` VARCHAR(255) NULL,
  `imgProducto` VARCHAR(255) NULL,
  `Cupones_idCupones` INT NULL,
  PRIMARY KEY (`idProducto`, `Cupones_idCupones`),
  CONSTRAINT `fk_Productos_Cupones1`
    FOREIGN KEY (`Cupones_idCupones`)
    REFERENCES `vsarena`.`Cupones` (`idCupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Productos_Cupones1_idx` ON `vsarena`.`Productos` (`Cupones_idCupones` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`DetallesVentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`DetallesVentas` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`DetallesVentas` (
  `Ventas_idVenta` INT NOT NULL,
  `Productos_idProducto` INT NOT NULL,
  `cantidadProducto` INT NOT NULL,
  PRIMARY KEY (`Ventas_idVenta`, `Productos_idProducto`),
  CONSTRAINT `fk_DetallesVenta_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `vsarena`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallesVenta_Productos_Ventas1`
    FOREIGN KEY (`Ventas_idVenta`)
    REFERENCES `vsarena`.`Ventas` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DetallesVenta_has_Productos_Productos1_idx` ON `vsarena`.`DetallesVentas` (`Productos_idProducto` ASC);

CREATE INDEX `fk_DetallesVenta_Productos_Ventas1_idx` ON `vsarena`.`DetallesVentas` (`Ventas_idVenta` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Premios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Premios` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Premios` (
  `idPremio` INT NOT NULL AUTO_INCREMENT,
  `nombrePremio` VARCHAR(255) NULL,
  `Premio` VARCHAR(255) NULL,
  `Torneos_idTorneos` INT NOT NULL,
  `Equipos_idEquipo` INT NULL,
  PRIMARY KEY (`idPremio`, `Torneos_idTorneos`, `Equipos_idEquipo`),
  CONSTRAINT `fk_Premios_Torneos1`
    FOREIGN KEY (`Torneos_idTorneos`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Premios_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `vsarena`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Premios_Torneos1_idx` ON `vsarena`.`Premios` (`Torneos_idTorneos` ASC);

CREATE INDEX `fk_Premios_Equipos1_idx` ON `vsarena`.`Premios` (`Equipos_idEquipo` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Enfrentamientos_Equipos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Enfrentamientos_Equipos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Enfrentamientos_Equipos` (
  `Enfrentamientos_idEnfrentamientos` INT NOT NULL,
  `Equipos_idEquipo` INT NOT NULL,
  PRIMARY KEY (`Enfrentamientos_idEnfrentamientos`, `Equipos_idEquipo`),
  CONSTRAINT `fk_Enfrentamientos_has_Equipos_Enfrentamientos1`
    FOREIGN KEY (`Enfrentamientos_idEnfrentamientos`)
    REFERENCES `vsarena`.`Enfrentamientos` (`idEnfrentamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfrentamientos_has_Equipos_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `vsarena`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Enfrentamientos_has_Equipos_Equipos1_idx` ON `vsarena`.`Enfrentamientos_Equipos` (`Equipos_idEquipo` ASC);

CREATE INDEX `fk_Enfrentamientos_has_Equipos_Enfrentamientos1_idx` ON `vsarena`.`Enfrentamientos_Equipos` (`Enfrentamientos_idEnfrentamientos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Imagenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Imagenes` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Imagenes` (
  `idImagen` INT NOT NULL AUTO_INCREMENT,
  `imagen` VARCHAR(255) NULL,
  `Juegos_idJuegos` INT NULL,
  `Productos_idProductos` INT NULL,
  PRIMARY KEY (`idImagen`, `Juegos_idJuegos`, `Productos_idProductos`),
  CONSTRAINT `fk_Imagenes_Juegos1`
    FOREIGN KEY (`Juegos_idJuegos`)
    REFERENCES `vsarena`.`Juegos` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imagenes_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `vsarena`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Imagenes_Juegos1_idx` ON `vsarena`.`Imagenes` (`Juegos_idJuegos` ASC);

CREATE INDEX `fk_Imagenes_Productos1_idx` ON `vsarena`.`Imagenes` (`Productos_idProductos` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Equipos_has_Torneos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Equipos_has_Torneos` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Equipos_has_Torneos` (
  `Equipos_idEquipo` INT NOT NULL,
  `Torneos_idTorneo` INT NOT NULL,
  PRIMARY KEY (`Equipos_idEquipo`, `Torneos_idTorneo`),
  CONSTRAINT `fk_Equipos_has_Torneos_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `vsarena`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_has_Torneos_Torneos1`
    FOREIGN KEY (`Torneos_idTorneo`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipos_has_Torneos_Torneos1_idx` ON `vsarena`.`Equipos_has_Torneos` (`Torneos_idTorneo` ASC);

CREATE INDEX `fk_Equipos_has_Torneos_Equipos1_idx` ON `vsarena`.`Equipos_has_Torneos` (`Equipos_idEquipo` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Noticias` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Noticias` (
  `idNoticia` INT NOT NULL,
  `tituloNoticia` VARCHAR(255) NULL,
  `imgNoticia` VARCHAR(255) NULL,
  `contenidoNoticia` VARCHAR(255) NULL,
  `fechaNoticia` VARCHAR(255) NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idNoticia`, `Usuarios_idUsuario`),
  CONSTRAINT `fk_Noticias_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `vsarena`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Noticias_Usuarios1_idx` ON `vsarena`.`Noticias` (`Usuarios_idUsuario` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Tags` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Tags` (
  `idTag` INT NOT NULL,
  `tag` VARCHAR(255) NULL,
  PRIMARY KEY (`idTag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vsarena`.`Tags_has_Noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Tags_has_Noticias` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Tags_has_Noticias` (
  `Tags_idTag` INT NOT NULL,
  `Noticias_idNoticia` INT NOT NULL,
  PRIMARY KEY (`Tags_idTag`, `Noticias_idNoticia`),
  CONSTRAINT `fk_Tags_has_Noticias_Tags1`
    FOREIGN KEY (`Tags_idTag`)
    REFERENCES `vsarena`.`Tags` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tags_has_Noticias_Noticias1`
    FOREIGN KEY (`Noticias_idNoticia`)
    REFERENCES `vsarena`.`Noticias` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tags_has_Noticias_Noticias1_idx` ON `vsarena`.`Tags_has_Noticias` (`Noticias_idNoticia` ASC);

CREATE INDEX `fk_Tags_has_Noticias_Tags1_idx` ON `vsarena`.`Tags_has_Noticias` (`Tags_idTag` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vsarena`.`Comentarios` ;

CREATE TABLE IF NOT EXISTS `vsarena`.`Comentarios` (
  `idComentario` INT NOT NULL,
  `contenidoComentario` VARCHAR(255) NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  `Noticias_idNoticia` INT NULL,
  `Productos_idProducto` INT NULL,
  PRIMARY KEY (`idComentario`, `Usuarios_idUsuario`, `Noticias_idNoticia`, `Productos_idProducto`),
  CONSTRAINT `fk_Comentarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `vsarena`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Noticias1`
    FOREIGN KEY (`Noticias_idNoticia`)
    REFERENCES `vsarena`.`Noticias` (`idNoticia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `vsarena`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comentarios_Usuarios1_idx` ON `vsarena`.`Comentarios` (`Usuarios_idUsuario` ASC);

CREATE INDEX `fk_Comentarios_Noticias1_idx` ON `vsarena`.`Comentarios` (`Noticias_idNoticia` ASC);

CREATE INDEX `fk_Comentarios_Productos1_idx` ON `vsarena`.`Comentarios` (`Productos_idProducto` ASC);


-- -----------------------------------------------------
-- Table `vsarena`.`Torneos_has_Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsarena`.`Torneos_has_Equipos` (
  `Torneos_idTorneo` INT NOT NULL,
  `Equipos_idEquipo` INT NOT NULL,
  PRIMARY KEY (`Torneos_idTorneo`, `Equipos_idEquipo`),
  INDEX `fk_Torneos_has_Equipos_Equipos1_idx` (`Equipos_idEquipo` ASC),
  INDEX `fk_Torneos_has_Equipos_Torneos1_idx` (`Torneos_idTorneo` ASC),
  CONSTRAINT `fk_Torneos_has_Equipos_Torneos1`
    FOREIGN KEY (`Torneos_idTorneo`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Torneos_has_Equipos_Equipos1`
    FOREIGN KEY (`Equipos_idEquipo`)
    REFERENCES `vsarena`.`Equipos` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


-- -----------------------------------------------------
-- Table `vsarena`.`Torneos_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vsarena`.`Torneos_has_Usuarios` (
  `Torneos_idTorneo` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Torneos_idTorneo`, `Usuarios_idUsuario`),
  INDEX `fk_Torneos_has_Usuarios_Usuarios1_idx` (`Usuarios_idUsuario` ASC),
  INDEX `fk_Torneos_has_Usuarios_Torneos1_idx` (`Torneos_idTorneo` ASC),
  CONSTRAINT `fk_Torneos_has_Usuarios_Torneos1`
    FOREIGN KEY (`Torneos_idTorneo`)
    REFERENCES `vsarena`.`Torneos` (`idTorneo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Torneos_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `vsarena`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

